//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eApp.Web.Admin.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class iproductprice
    {
        public int Id { get; set; }
        public string itemcode { get; set; }
        public string sellingprice { get; set; }
        public string purchasingprice { get; set; }
        public string vatprice { get; set; }
        public string remarks { get; set; }
        public string status { get; set; }
    }
}
