//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eApp.Web.Admin.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class iproduct
    {
        public int Id { get; set; }
        public string itemcode { get; set; }
        public string barcode { get; set; }
        public string modelno { get; set; }
        public string serialno { get; set; }
        public string arname { get; set; }
        public string enname { get; set; }
        public string arshortname { get; set; }
        public string enshortname { get; set; }
        public string size { get; set; }
        public string unit { get; set; }
        public string remarks { get; set; }
        public string status { get; set; }
    }
}
