//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eApp.Web.Admin.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class nservice
    {
        public int Id { get; set; }
        public string servicescode { get; set; }
        public string servicename { get; set; }
        public string description { get; set; }
        public string departmentid { get; set; }
        public string nprice { get; set; }
        public string sprice { get; set; }
        public string minutes { get; set; }
        public string hours { get; set; }
        public string fixedcommission { get; set; }
        public string remarks { get; set; }
        public string status { get; set; }
    }
}
