//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eApp.Web.Admin.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class xbranchsale
    {
        public int Id { get; set; }
        public string branchcode { get; set; }
        public string paymenttype { get; set; }
        public string servicecode { get; set; }
        public string servicecodediscount { get; set; }
        public string totalamount { get; set; }
        public string amountgiven { get; set; }
        public string amountbalance { get; set; }
        public System.DateTime paymentcreated { get; set; }
        public System.DateTime serviceagentid { get; set; }
        public System.DateTime cashieragendid { get; set; }
        public string remarks { get; set; }
        public string status { get; set; }
    }
}
