//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eApp.Web.Admin.ADO
{
    using System;
    using System.Collections.Generic;
    
    public partial class xbranchstock
    {
        public int Id { get; set; }
        public string branchcode { get; set; }
        public string itemcode { get; set; }
        public string quantityordered { get; set; }
        public string quantityonhand { get; set; }
        public string quantityused { get; set; }
        public System.DateTime lastdatemodified { get; set; }
        public string remarks { get; set; }
        public string status { get; set; }
    }
}
